x-service-backend-adidas: &service-backend-adidas
  build:
    dockerfile: Dockerfile
    context: ./backend
  restart: always
  command: |
    sh -c "
    uv run -m uvicorn main:app --host "0.0.0.0" --port  20000 --reload
    "
  volumes:
    - ./backend/app:/app
  networks:
    - main_network

services:
  backend_adidas:
    <<: *service-backend-adidas
    container_name: backend_adidas
    hostname: backend_adidas
    ports:
      - "17777:20000"

  backend_adidas2:
    <<: *service-backend-adidas
    container_name: backend_adidas2
    hostname: backend_adidas2
    ports:
      - "18888:20000"

  nginx_adidas:
    image: nginx:alpine
    container_name: nginx_adidas
    restart: always
    ports:
      - "80:80"
    networks:
      - main_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend_adidas
      - backend_adidas2

networks:
  main_network:
    driver: bridge